fix error_at_line() support for musl libc
Add a missing ; for the non gnu libc case.

This fixes the compile error when bulding with musl libc:

In file included from perror.c:28:0:
au_util.h: In function 'error_at_line':
au_util.h:62:1: warning: empty declaration
 struct mntent;
 ^~~~~~
au_util.h:66:1: warning: empty declaration
 union aufs_brinfo;
 ^~~~~
au_util.h:78:1: warning: empty declaration
 enum {
 ^~~~
au_util.h:97:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
 {
 ^

Signed-off-by: Natanael Copa <natanael.copa@docker.com>